/**
 * Plugin-compatibility recovery for the desktop shell.
 *
 * The Host is a pure `dsh web` boot: one unloadable plugin bundle aborts the
 * whole profile (installFailLoud in dsh-app-boot), which surfaced to desktop
 * users as an opaque stack trace on the splash window. This module turns that
 * failure into a machine-readable list of offending bundles so the shell can
 * relaunch with exactly those bundles disabled.
 *
 * Disabling goes through a cordis `--patch` overlay carrying `disabled: true`
 * per loader entry — dsh's own recovery channel. The loader short-circuits a
 * disabled entry before importing it, so a bundle whose module cannot be
 * imported never gets imported. It needs no network and mutates nothing the
 * user owns, unlike `dsh.profile.bundles`, which `dsh plugin` derives from
 * `dependencies` and would silently restore on the next plugin install.
 */

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

/** One loader entry whose import failed, with the reason dsh reported. */
export interface FailingPlugin {
  /** cordis loader entry id, i.e. the --patch target (openviking). */
  readonly entryId: string;
  /** Package that owns the entry (dsh-openviking). */
  readonly packageName: string;
  /** Raw one-line reason dsh emitted after the colon. */
  readonly reason: string;
}

/** How the shell should react to a Host startup failure. */
export type HostFailure =
  | { readonly kind: "incompatible-plugin"; readonly plugins: FailingPlugin[] }
  | { readonly kind: "not-plugin-related" };

/** Shape: failed to import loader entry <id> (<package>): <reason> */
const IMPORT_FAILURE_RE =
  /failed to import loader entry ([^\s(]+) \(([^)]+)\): ?([^\n\r]*)/gu;

/** Signals that the profile tree never finished loading. */
const PLUGIN_TREE_FAILED_RE =
  /plugin tree failed to load|loader entries failed to apply|failed to apply loader entry include/u;

/**
 * Extract every plugin bundle dsh could not import from captured Host output.
 *
 * Deliberately conservative: it only claims a plugin conflict when it can name
 * the offending entries, so a port conflict or a missing Node is never
 * misdiagnosed as a bad plugin.
 */
export function classifyHostFailure(output: string): HostFailure {
  const plugins: FailingPlugin[] = [];
  const seen = new Set<string>();
  for (const match of output.matchAll(IMPORT_FAILURE_RE)) {
    const entryId = match[1]?.trim();
    const packageName = match[2]?.trim();
    if (entryId === undefined || packageName === undefined) continue;
    if (seen.has(entryId)) continue;
    seen.add(entryId);
    plugins.push({ entryId, packageName, reason: (match[3] ?? "").trim() });
  }
  if (plugins.length > 0) return { kind: "incompatible-plugin", plugins };
  return { kind: "not-plugin-related" };
}

/**
 * Whether a startup failure smells like a plugin problem.
 *
 * Messaging aid only: recovery needs named entries (classifyHostFailure), so an
 * unparseable plugin-tree failure still reports honestly instead of claiming a
 * bundle was disabled.
 */
export function looksPluginRelated(output: string): boolean {
  return PLUGIN_TREE_FAILED_RE.test(output);
}

/** Render the cordis overlay that disables exactly these loader entries. */
export function renderSafeModePatch(entryIds: readonly string[]): string {
  const unique = [...new Set(entryIds.filter((id) => id !== ""))];
  const header = [
    "# Generated by DSH Desktop. The plugins listed here are incompatible with",
    "# the active dsh kernel and are disabled so the app can start.",
    "# Manage them from the tray or app menu (已停用插件). Do not edit by hand.",
    "",
  ].join("\n");
  if (unique.length === 0) return header + "[]\n";
  const rows = unique.map(
    (id) => `- id: ${quoteYamlScalar(id)}\n  disabled: true`,
  );
  return header + rows.join("\n") + "\n";
}

/** Words a YAML 1.1 parser would coerce into something other than a string. */
const YAML_AMBIGUOUS = new Set([
  "true",
  "false",
  "yes",
  "no",
  "on",
  "off",
  "null",
  "~",
  "y",
  "n",
]);

/**
 * Emit an entry id as a plain scalar only when no YAML parser could read it as
 * anything but that string. Real loader entry ids are plain kebab-case, so this
 * leaves the common file untouched and quotes just the awkward cases.
 */
function quoteYamlScalar(value: string): string {
  const plain = /^[A-Za-z_][A-Za-z0-9_.@-]*$/u;
  if (plain.test(value) && !YAML_AMBIGUOUS.has(value.toLowerCase()))
    return value;
  return `'${value.replace(/'/gu, "''")}'`;
}

/**
 * Translate a dsh import error into a line a user can act on.
 *
 * The dominant real-world shape is a missing named export: the plugin was built
 * against an older kernel API. Naming the symbol is what makes the situation
 * searchable for the plugin author.
 */
export function explainReason(reason: string): string {
  const missingExport =
    /does not provide an export named ['"]([^'"]+)['"]/u.exec(reason);
  if (missingExport?.[1] !== undefined) {
    const mod = /The requested module ['"]([^'"]+)['"]/u.exec(reason)?.[1];
    const where = mod === undefined ? "" : `（来自 ${mod}）`;
    return `插件要求的导出 ${missingExport[1]} 在当前内核中已不存在${where}，属于插件与 dsh 内核版本不兼容`;
  }
  if (/Cannot find (?:package|module)/u.test(reason)) {
    return "插件的依赖缺失或未安装，可尝试重新安装该插件";
  }
  if (/is not defined|not a function|Cannot read propert/iu.test(reason)) {
    return "插件运行时访问了内核不具备的接口，属于版本不兼容";
  }
  return reason === "" ? "插件导入失败" : reason;
}

/** Persistent record of one bundle the shell had to disable. */
export interface DisabledPlugin {
  readonly entryId: string;
  readonly packageName: string;
  readonly reason: string;
  readonly disabledAt: string;
}

/**
 * Merge newly detected failures into the disabled set.
 *
 * @returns the next set, or undefined when nothing was added — which is how the
 * boot loop detects a stalled recovery and stops retrying.
 */
export function withDisabled(
  current: readonly DisabledPlugin[],
  failures: readonly FailingPlugin[],
  now: string,
): DisabledPlugin[] | undefined {
  const known = new Set(current.map((entry) => entry.entryId));
  const added = failures.filter((entry) => !known.has(entry.entryId));
  if (added.length === 0) return undefined;
  return [
    ...current,
    ...added.map<DisabledPlugin>((entry) => ({
      entryId: entry.entryId,
      packageName: entry.packageName,
      reason: entry.reason,
      disabledAt: now,
    })),
  ];
}

/** Drop one entry when the user re-enables a plugin; undefined when absent. */
export function withoutDisabled(
  current: readonly DisabledPlugin[],
  entryId: string,
): DisabledPlugin[] | undefined {
  if (!current.some((entry) => entry.entryId === entryId)) return undefined;
  return current.filter((entry) => entry.entryId !== entryId);
}

/** JSON state file naming every bundle the shell disabled. */
export const SAFE_STATE_FILE = "plugin-safe-mode.json";
/** Cordis overlay regenerated from that state and passed as --patch. */
export const SAFE_PATCH_FILE = "plugin-safe-mode.patch.yml";

function safeStatePath(userDataDir: string): string {
  return join(userDataDir, SAFE_STATE_FILE);
}

/** Path of the overlay the Host is booted with (undefined when nothing is off). */
export function safePatchPath(userDataDir: string): string | undefined {
  return readSafeMode(userDataDir).length === 0
    ? undefined
    : join(userDataDir, SAFE_PATCH_FILE);
}

/** Load the disabled set; a corrupt or absent file means nothing is disabled. */
export function readSafeMode(userDataDir: string): DisabledPlugin[] {
  try {
    const raw = JSON.parse(readFileSync(safeStatePath(userDataDir), "utf8"));
    const rows: unknown = Array.isArray(raw) ? raw : raw?.disabled;
    if (!Array.isArray(rows)) return [];
    return rows
      .map((row): DisabledPlugin | undefined => {
        if (typeof row !== "object" || row === null) return undefined;
        const value = row as Record<string, unknown>;
        const entryId = value.entryId;
        const packageName = value.packageName;
        if (typeof entryId !== "string" || entryId === "") return undefined;
        return {
          entryId,
          packageName: typeof packageName === "string" ? packageName : entryId,
          reason: typeof value.reason === "string" ? value.reason : "",
          disabledAt:
            typeof value.disabledAt === "string" ? value.disabledAt : "",
        };
      })
      .filter((row): row is DisabledPlugin => row !== undefined);
  } catch {
    return [];
  }
}

/**
 * Persist the disabled set and regenerate the overlay it implies.
 *
 * @returns the patch path the next Host boot should pass, or undefined when
 * nothing is disabled (so the caller drops --patch entirely).
 */
export function writeSafeMode(
  userDataDir: string,
  disabled: readonly DisabledPlugin[],
): string | undefined {
  mkdirSync(userDataDir, { recursive: true });
  writeFileSync(
    safeStatePath(userDataDir),
    JSON.stringify({ disabled }, null, 2) + "\n",
    "utf8",
  );
  writeFileSync(
    join(userDataDir, SAFE_PATCH_FILE),
    renderSafeModePatch(disabled.map((entry) => entry.entryId)),
    "utf8",
  );
  return disabled.length === 0 ? undefined : join(userDataDir, SAFE_PATCH_FILE);
}
/**
 * The recovery loop itself, injected so it is testable without Electron.
 *
 * @param startup - begins a Host generation; rejects with the captured output.
 * @param state - current disabled set plus the commit for a new one.
 * @param report - progress sink for the splash window.
 * @returns bundles disabled during this call (empty when none were needed).
 */
export async function startWithPluginRecovery(options: {
  startup: (attempt: number) => Promise<unknown>;
  getDisabled: () => readonly DisabledPlugin[];
  commit: (next: readonly DisabledPlugin[]) => void;
  report?: (count: number) => void;
  now?: () => string;
  maxRounds?: number;
}): Promise<DisabledPlugin[]> {
  const { startup, getDisabled, commit, report, now } = options;
  const maxRounds = options.maxRounds ?? 8;
  const newlyDisabled: DisabledPlugin[] = [];
  for (let attempt = 0; ; attempt++) {
    try {
      await startup(attempt);
      return newlyDisabled;
    } catch (error) {
      const output = error instanceof Error ? error.message : String(error);
      const failure = classifyHostFailure(output);
      if (failure.kind !== "incompatible-plugin" || attempt >= maxRounds) {
        throw startupErrorForUser(output, error);
      }
      const next = withDisabled(
        getDisabled(),
        failure.plugins,
        (now ?? (() => new Date().toISOString()))(),
      );
      if (next === undefined) throw startupErrorForUser(output, error);
      newlyDisabled.push(...next.slice(getDisabled().length));
      commit(next);
      report?.(next.length);
    }
  }
}

/**
 * Turn an unattributable plugin failure into something a user can act on.
 *
 * The Host dies with a raw ESM stack that names neither the plugin nor the fix.
 * With bundles identified, the caller already disabled them, so reaching here
 * means recovery did not converge and the message says exactly that.
 */
export function startupErrorForUser(output: string, cause: unknown): Error {
  const wrapped = { cause } as { cause: unknown };
  if (classifyHostFailure(output).kind === "incompatible-plugin") {
    return new Error(
      "部分插件与当前 dsh 内核不兼容，自动停用后仍无法启动。请在插件中心更新或卸载最近安装的插件后重试。",
      wrapped,
    );
  }
  if (looksPluginRelated(output)) {
    return new Error(
      "dsh 插件加载失败，客户端无法启动。请更新或卸载最近安装的插件后重试。",
      wrapped,
    );
  }
  return cause instanceof Error ? cause : new Error(output, wrapped);
}

/** Splash-window progress line shown while the recovery relaunches the Host. */
export function recoveringDetail(count: number): string {
  return `已自动停用 ${String(count)} 个与内核不兼容的插件，正在重新启动…`;
}
